media: public
content: 
  - name: posts
    label: Posts
    type: collection
    path: 'src/pages'
    filename: '{title}.mdx'
    view:
      fields: [ title, published, date ]
      primary: title
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: seoTitle
        label: SEO Title
        type: string
      - name: description
        label: Description
        type: string
      - name: publishedOn
        label: Published On
        type: date
      - name: layout
        label: Layout
        type: string
      - name: body
        label: Body
        type: code
        options:
          language: react
