media: public
content: 
  - name: posts
    label: Posts
    type: collection
    path: 'src/pages'
    filename: '{title}.mdx'
    view:
      fields: [ title, published, date ]
      primary: title
    fields:
      - name: body
        label: Body
        type: code
